### ISSUE TITLE
Possible Ruby implementation

### ISSUE THREAD

**Issue by haberbyte** [evanw/kiwi#16]
Hey @evanw,

I was looking for a small and lightweight binary schema to use with emscripten (json bloats the binary size quite a bit for me), so I thought of using flatbuffers.

But this library is even more lightweight and simple, so I started experimenting with it.
Neither flatbuffers nor kiwi has a ruby implementation, though. I was thinking of maybe adding a ruby encoder/decoder for it because my use-case would be a Rails backend.

How stable do you think the format is in its current form?
I wonder if it is in use at Figma, or if this is just at an "experimental" state?

**Comment by evanw** [comment]
This is very stable. It's currently the basis for all of Figma's file data, both on disk and on the wire between the client and server. We may move off of it to another format one day, but I doubt very much that we will change the format.

Are you sure you'd want codec written in Ruby vs. a native extension for Ruby? I have limited experience with Ruby but I remember running into pretty severe performance issues with a Ruby-based parser for something (maybe JSON?) and switching to a native extension for Ruby dramatically improved performance. Of course this wouldn't matter if the messages are small, but might start to matter a lot if the messages get big.

**Comment by haberbyte** [comment]
Good point, I guess a native extension would be better.
`kiwi.h` is really straight forward as well, so building one should not be that hard.

I am still just experimenting with the format in emscripten, but as soon as I need to actually save stuff in the backend I will make a small ruby gem.

I will close this issue for now. As soon as I have something real, I can open up a PR to add docs or a link for ruby.

**Comment by haberbyte** [comment]
Hey @evanw ... i created a ruby implementation here: https://github.com/haberbyte/kiwi-schema

It is still kind of WIP, but basically already works. I used the rust implementation as a basis and pretty much re-implemented the tests in ruby.
It is probably not very performant, but it was a fun exercise, and i thought i shared it.

What should i put as the licence? Once I polish this a bit more, maybe it can be added as a link to the other implementations in the README here as well. What do you think?
