### ISSUE TITLE
Using kiwi messages for Emscripten JS <-> C++ <-> JS bridge

### ISSUE THREAD

**Issue by haberbyte** [evanw/kiwi#19]
Hey @evanw, this is not really an issue with kiwi, but I have related questions about using it in a project. I was hoping to get some pointers from you.

I am using kiwi to encode data on JS side into a buffer of Uint8s, then i `_malloc` some space, copy the data over, and decode the data again on C++ side, followed by `_free`. Simple and easy.

What I am wondering is, how do I do it the opposite way?
From JS point of view, i don't know how the size of a message is before encoding it in C++.
So I essentially need to have a method that creates a new object, stores the pointer to it, then tells it to populate a `kiwi::ByteBuffer`, and then tell it to give me its size and memory location.

Is that the right way to handle it? I wonder how Figma deals with bridging JS/C++ data, is the source of truth in JS-land, or is the source of truth in C++-land? Do you reuse the classes of the kiwi schema internally, or is that merely for data exchange. For example, I have a Color class both in my kiwi schema and in my project. I convert the kiwi message to my own classes.

Also wondering if the `IndirectBuffer` could be useful here.

Sorry for the big brain dump, any advice is highly appreciated. 😊

**Comment by evanw** [comment]
> What I am wondering is, how do I do it the opposite way?

There are various ways of doing JS-to-C++ calls:

* JS has to call into C++ twice, once to get the pointer and once to get the size. JS calls `Module._free` once on the pointer when it's done with it. C++ needs to store a reference to the data somewhere in between calls.

* JS calls C++ once and gets a returned pointer but during the call into C++, C++ calls back into JS and gives it the size. Then by the time the C++ call returns, JS has the pointer and the size. JS calls `Module._free` on the pointer when it's done.

* JS calls C++ once and C++ returns a pointer to a small block of memory with the size and another pointer to the actual data. JS has to call `Module._free` twice.

* JS calls C++ once and C++ returns a pointer to a length-prefixed block of memory (a single buffer with the length followed by the data). JS only has to call `Module._free` once.

* JS calls C++ once and gets the handle of an `IndirectBuffer` that was filled in by C++. JS later tells C++ that it's done with the handle so C++ can delete it.

With all of these, there's a trick you can do to avoid needing to manually free the memory on the JS side: if you can guarantee that JS always copies the info it needs immediately (i.e. reentrancy is not a concern), then you can just have C++ keep this memory in a global and have C++ free the memory from the previous JS-to-C++ call when the next JS-to-C++ call happens.

> I wonder how Figma deals with bridging JS/C++ data, is the source of truth in JS-land, or is the source of truth in C++-land?

That depends on your application. Some of our data is owned by JS and some of it is owned by C++.

> Do you reuse the classes of the kiwi schema internally, or is that merely for data exchange.

The C++ kiwi library allocates things in a short-lived memory pool, so it's not great for long-lived data. It makes the most sense to convert the kiwi message to your own data structures in C++.

**Comment by haberbyte** [comment]
Wow, thank you so much for this detailed explanation ❤️, it helped me a lot.

I got my data exchange working in a slight variation of these i guess:

-  JS calls C++ once, then C++ creates a buffer and populates it, and calls back into JS with it's ptr and size, JS saves it in a variable immedtiately, and by the time the first call is done, the data is already copied and C++ frees the temporary buffer again.

Maybe this is more or less what you described, sort of the trick you mentioned reversed.
