### ISSUE TITLE
Is there any support for Golang?

### ISSUE THREAD

**Issue by lrioo** [evanw/kiwi#28]
Hi @evanw , we are looking for a lighter Codec for our Golang project. 

Is Kiwi with any support for Golang? 

May be you can provide a copy of codec rules of Kiwi, if not. 

Thx.

**Comment by evanw** [comment]
No, kiwi does not currently support Go. I don't have time to document the format right now but the format is pretty simple and should be relatively self-evident from the code. Here is the main encoding loop, for example:

https://github.com/evanw/kiwi/blob/1a82ea6592ff25f26e35ca69e58c98852072eae9/rust/src/lib.rs#L1015-L1063

**Comment by lrioo** [comment]
Thanks anyway. I will try to convert a Codec from cpp.ts.

Maybe create a PR when I finished 😄
