### ISSUE TITLE
How do I make a field in a `struct` optional?

### ISSUE THREAD

**Issue by hamirmahal** [evanw/kiwi#31]
Some `struct MarkerSchema`s have the optional `string tooltipLabel` field, and others don't.

How do I indicate to `kiwi` that the `string tooltipLabel` field is optional?

![image](https://user-images.githubusercontent.com/43425812/168495959-c4b56009-8b98-4746-a86f-23e44b57bdc3.png)

**Comment by evanw** [comment]
You can’t do that. The point of using a `struct` is to avoid unnecessary overhead when you know all fields are non-optional. You should be using `message` instead. This is documented here: https://github.com/evanw/kiwi#user-types.

**Comment by hamirmahal** [comment]
Ah, that helped me get things working at http://evanw.github.io/kiwi/.

Thank you for your response!
